name: uyobooks
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0-165.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animate_do: ^3.0.2
  smooth_page_indicator: ^1.0.0+2
  lottie: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/anim/


  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/lora/Lora-Regular.ttf
          weight: 400

    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 800
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 400
  #
